# Generated by Django 4.1.1 on 2022-09-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_auto_20220918_1735"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teachers",
            new_name="CourseTeachers",
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created",),
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
